club_77/club_77/urls.py
from django.contrib import admin
from django.urls import path, include
from página_principal import views as home

urlpatterns = [
    path('', home.homepage, name='home'),
    path('admin/', admin.site.urls),
    path('produtos/', include('produtos.urls')),
    path('clientes/', include('clientes.urls')),
    path('vendas/', include('vendas.urls'))
]

club_77/vendas/urls.py
from django.urls import path
from . import views

app_name = 'vendas'

urlpatterns = [
    path('', views.lista_vendas, name='lista_vendas'),
    path('adicionar/', views.adicionar_venda, name='adicionar_venda'),
    path('detalhes/<int:venda_id>/', views.detalhes_venda, name='detalhes_venda'),
    path('editar/<int:venda_id>/', views.editar_venda, name='editar_venda'),
]

club_77/vendas/models.py
from django.db import models
from produtos.models import Produto
from clientes.models import Cliente


class Venda(models.Model):
    data_venda = models.DateTimeField(auto_now_add=True)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    total = models.DecimalField(decimal_places=2, max_digits=8)


class ItemVenda(models.Model):
    venda = models.ForeignKey(Venda, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.IntegerField()

club_77/vendas/forms.py
from django import forms
from .models import Venda
from .models import ItemVenda


class VendaForm(forms.ModelForm):
    class Meta:
        model = Venda
        fields = ['cliente', 'total']


class ItemVendaForm(forms.ModelForm):
    class Meta:
        model = ItemVenda
        fields = ['produto', 'quantidade']

club_77/vendas/views.py
from django.db import transaction
from django.shortcuts import render, redirect, get_object_or_404

from .forms import VendaForm, ItemVendaForm
from .models import Venda, ItemVenda


def lista_vendas(request):
    vendas = Venda.objects.all()
    return render(request, 'vendas/lista_vendas.html', {'vendas': vendas})


def adicionar_venda(request):
    if request.method == 'POST':
        venda_form = VendaForm(request.POST)
        item_form = ItemVendaForm(request.POST)
        if venda_form.is_valid() and item_form.is_valid():
            venda = venda_form.save()
            item = item_form.save(commit=False)
            item.venda = venda
            item.save()
            return redirect('lista_vendas')
    else:
        venda_form = VendaForm()
        item_form = ItemVendaForm()
    return render(request, 'vendas/adicionar_venda.html', {'venda_form': venda_form, 'item_form': item_form})

def detalhes_venda(request, venda_id):
    venda = get_object_or_404(Venda, pk=venda_id)
    return render(request, 'vendas/detalhes_venda.html', {'venda': venda})


def editar_venda(request, venda_id):
    venda = Venda.objects.get(id=venda_id)
    if request.method == 'POST':
        venda_form = VendaForm(request.POST, instance=venda, prefix='venda')
        if venda_form.is_valid():
            with transaction.atomic():
                venda = venda_form.save()

                # Atualizar o estoque de cada item de venda
                for item in venda.itemvenda_set.all():
                    produto = item.produto
                    quantidade_vendida_anterior = item.quantidade

                    # Reverter o estoque do produto para o valor anterior
                    produto.quantidade += quantidade_vendida_anterior
                    produto.save()

                    # Atualizar o estoque do produto de acordo com a nova quantidade
                    quantidade_vendida_nova = request.POST.get(f'item_venda_{item.id}-quantidade')
                    produto.quantidade -= int(quantidade_vendida_nova)
                    produto.save()

            return redirect('lista_vendas')
    else:
        venda_form = VendaForm(instance=venda, prefix='venda')

        itens_venda = ItemVenda.objects.filter(venda=venda)
        item_venda_forms = [ItemVendaForm(instance=item, prefix=f'item_venda_{item.id}') for item in itens_venda]
    return render(request, 'vendas/editar_venda.html', {'venda_form': venda_form, 'item_venda_forms': item_venda_forms, 'venda': venda})

club_77/vendas/templates/vendas/adicionar_venda.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adicionar Venda</title>
    <link rel="stylesheet" type="text/css" href="{% static 'vendas/styles_adicionar_vendas.css' %}">
</head>
<body>
    <div class="container">
        <h1>Adicionar Venda</h1>
        <form method="post">
            {% csrf_token %}
            <h2>Dados da Venda</h2>
            {{ venda_form.as_p }}
            <h2>Itens da Venda</h2>
            {{ item_form.as_p }}
            <button type="submit">Adicionar Venda</button>
        </form>
        <div class="button-back">
            <a href="{% url 'vendas:lista_vendas' %}">Voltar para Lista de Vendas</a>
        </div>
    </div>
</body>
</html>

club_77/vendas/templates/vendas/detalhes_venda.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalhes da Venda</title>
    <link rel="stylesheet" type="text/css" href="{% static 'vendas/styles_detalhes_venda.css' %}">
</head>
<body>
    <div class="container">
        <h1>Detalhes da Venda</h1>
        <p>Cliente: {{ venda.cliente }}</p>
        <p>Total: {{ venda.total }}</p>
        <h2>Itens de Venda</h2>
        <ul>
            {% for item in venda.itemvenda_set.all %}
                <li>Produto: {{ item.produto }}</li>
                <li>Quantidade: {{ item.quantidade }}</li>
            {% endfor %}
        </ul>
        <div class="button-back">
            <a href="{% url 'vendas:lista_vendas' %}">Voltar para Lista de Vendas</a>
        </div>
    </div>
</body>
</html>

club_77/vendas/templates/vendas/editar_venda.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Venda</title>
    <link rel="stylesheet" type="text/css" href="{% static 'vendas/styles_editar_venda.css' %}">
</head>
<body>
    <div class="container">
        <h1>Editar Venda</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="cliente">Cliente:</label>
                <input type="text" id="cliente" name="cliente" value="{{ venda.cliente }}">
            </div>
            <div class="form-group">
                <label for="total">Total:</label>
                <input type="number" id="total" name="total" value="{{ venda.total }}">
            </div>
            <!-- Adicione os campos para editar os itens de venda -->
            {% for item_venda_form in item_venda_forms %}
            <div class="item-venda">
                {{ item_venda_form.as_p }}
            </div>
            {% endfor %}
            <button type="submit">Salvar Alterações</button>
        </form>
        <div class="button-back">
            <a href="{% url 'vendas:lista_vendas' %}">Voltar para Lista de Vendas</a>
        </div>
    </div>
</body>
</html>

club_77/vendas/templates/vendas/lista_vendas.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Vendas</title>
    <link rel="stylesheet" type="text/css" href="{% static 'vendas/styles_lista_vendas.css' %}">
</head>
<body>
    <div class="container">
        <h1>Lista de Vendas</h1>
        <ul class="vendas-lista">
            {% for venda in vendas %}
                <li class="venda">
                    <div class="venda-info">
                        <p>Data da Venda: {{ venda.data_venda }}</p>
                        <p>Total: R$ {{ venda.total }}</p>
                    </div>
                    <div class="venda-botoes">
                        <a href="{% url 'vendas:detalhes_venda' venda.id %}" class="detalhes">Detalhes</a>
                        <a href="{% url 'vendas:editar_venda' venda.id %}" class="editar">Editar</a>
                    </div>
                </li>
            {% endfor %}
        </ul>
        <div class="adicionar-link">
            <a href="{% url 'vendas:adicionar_venda' %}">Adicionar Nova Venda</a>
            <a href="{% url 'home' %}">Voltar para o Menu Inicial</a>
        </div>
    </div>
</body>
</html>