club_77/club_77/urls.py
from django.contrib import admin
from django.urls import path, include
from página_principal import views as home

urlpatterns = [
    path('', home.homepage, name='home'),
    path('admin/', admin.site.urls),
    path('produtos/', include('produtos.urls')),
    path('clientes/', include('clientes.urls')),
    path('vendas/', include('vendas.urls'))
]

club_77/produtos/urls.py
from django.urls import path
from . import views

app_name = 'produtos'

urlpatterns = [
    path('', views.lista_produtos, name='lista_produtos'),
    path('detalhes/<int:id>/', views.detalhes_produto, name='detalhes_produto'),
    path('adicionar/', views.adicionar_produto, name='adicionar_produto'),
    path('editar/<int:produto_id>/', views.editar_produto, name='editar_produto'),
    path('confirmar_exclusao/<int:produto_id>/', views.confirmar_exclusao, name='confirmar_exclusao'),
    path('deletar/<int:produto_id>/', views.deletar_produto, name='deletar_produto'),
]

club_77/vendas/urls.py
from django.urls import path
from . import views

app_name = 'vendas'

urlpatterns = [
    path('', views.lista_vendas, name='lista_vendas'),
    path('adicionar/', views.adicionar_venda, name='adicionar_venda'),
    path('detalhes/<int:venda_id>/', views.detalhes_venda, name='detalhes_venda'),
    path('editar/<int:venda_id>/', views.editar_venda, name='editar_venda'),
]

club_77/produtos/models.py
from django.db import models

class Produto(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField()
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    estoque = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.nome

club_77/produtos/forms.py
from django import forms
from .models import Produto

class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = ['nome', 'descricao', 'preco', 'estoque']

club_77/produtos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Produto
from .forms import ProdutoForm


def lista_produtos(request):
    produtos = Produto.objects.all()
    return render(request, 'produtos/lista_produtos.html', {'produtos': produtos})


def detalhes_produto(request, id):
    produto = get_object_or_404(Produto, pk=id)
    return render(request, 'produtos/detalhes_produto.html', {'produto': produto})


def adicionar_produto(request):
    if request.method == 'POST':
        form = ProdutoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('produtos:lista_produtos')
    else:
        form = ProdutoForm()
    return render(request, 'produtos/adicionar_produto.html', {'form': form})


def editar_produto(request, produto_id):
    produto = get_object_or_404(Produto, pk=produto_id)
    if request.method == 'POST':
        form = ProdutoForm(request.POST, instance=produto)
        if form.is_valid():
            form.save()
            return redirect('produtos:lista_produtos')
    else:
        form = ProdutoForm(instance=produto)
    return render(request, 'produtos/editar_produto.html', {'form': form})


def confirmar_exclusao(request, produto_id):
    produto = get_object_or_404(Produto, pk=produto_id)
    if request.method == 'POST':
        produto.delete()
        return redirect('produtos:lista_produtos')
    return render(request, 'produtos/confirmar_exclusao_produto.html', {'produto': produto})


def deletar_produto(request, produto_id):
    produto = get_object_or_404(Produto, pk=produto_id)
    if request.method == 'GET':
        return redirect('produtos:confirmar_exclusao', produto_id=produto_id)
    return redirect('produtos:lista_produtos')

club_77/produtos/templates/produtos/adicionar_produto.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adicionar Produto</title>
    <link rel="stylesheet" type="text/css" href="{% static 'produtos/styles_adicionar.css' %}">
</head>
<body>
    <div class="container">
        <h1>Adicionar Produto</h1>
        <div class="formulario">
            <form method="post">
                {% csrf_token %}
                <label for="id_nome">Nome:</label>
                <input type="text" id="id_nome" name="nome" required>
                <label for="id_descricao">Descrição:</label>
                <textarea id="id_descricao" name="descricao" required></textarea>
                <label for="id_preco">Preço:</label>
                <input type="number" id="id_preco" name="preco" step="0.01" required>
                <label for="id_estoque">Estoque:</label>
                <input type="number" id="id_estoque" name="estoque" required>
                <button type="submit">Salvar</button>
            </form>
        </div>
        <div class="voltar-link">
            <a href="{% url 'produtos:lista_produtos' %}">Voltar para Lista de Produtos</a>
        </div>
    </div>
</body>
</html>

club_77/produtos/templates/produtos/confirmar_exclusao_produto.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmar Exclusão</title>
    <link rel="stylesheet" type="text/css" href="{% static 'produtos/styles_confirmacao.css' %}">
</head>
<body>
    <div class="container">
        <h1>Confirmar Exclusão</h1>
        <p>Você tem certeza que deseja excluir o produto "{{ produto.nome }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button class="btn" type="submit">Sim, Excluir</button>
            <a class="btn cancel-btn" href="{% url 'produtos:lista_produtos' %}">Cancelar</a>
        </form>
    </div>
</body>
</html>

club_77/produtos/templates/produtos/detalhes_produto.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalhes do Produto</title>
    <link rel="stylesheet" type="text/css" href="{% static 'produtos/styles_detalhes.css' %}">
</head>
<body>
    <div class="container">
        <div class="produto-details">
            <h1>Detalhes do Produto</h1>
            <h2>{{ produto.nome }}</h2>
            <p><strong>Preço:</strong> R$ {{ produto.preco }}</p>
            <p><strong>Descrição:</strong> {{ produto.descricao }}</p>
            <p><strong>Estoque:</strong> {{ produto.estoque }}</p>
            <!-- Adicione mais detalhes conforme necessário -->
        </div>
        <div class="voltar-link">
            <a href="{% url 'produtos:lista_produtos' %}">Voltar para Lista de Produtos</a>
        </div>
    </div>
</body>
</html>

club_77/produtos/templates/produtos/editar_produto.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Produto</title>
    <link rel="stylesheet" type="text/css" href="{% static 'produtos/styles_editar.css' %}">
</head>
<body>
    <h1>Editar Produto</h1>
    <div class="formulario">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Salvar Alterações</button>
        </form>
    </div>
    <div class="voltar-link">
            <a href="{% url 'produtos:lista_produtos' %}">Voltar para Lista de Produtos</a>
    </div>
</body>
</html>

club_77/produtos/templates/produtos/lista_produtos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Produtos</title>
    <link rel="stylesheet" type="text/css" href="{% static 'produtos/styles_lista.css' %}">
</head>
<body>
    <div class="container">
        <h1>Lista de Produtos</h1>
        {% for produto in produtos %}
            <div class="produto">
                <div>
                    <h2><a href="{% url 'produtos:detalhes_produto' produto.id %}">{{ produto.nome }}</a></h2>
                    <p class="preco">Preço: R$ {{ produto.preco }}</p>
                    <p>{{ produto.descricao }}</p>
                    <p class="estoque"> Estoque: {{ produto.estoque }}</p>
                </div>
                <div class="botoes">
                    <a href="{% url 'produtos:editar_produto' produto.id %}" class="editar">Editar</a>
                    <form action="{% url 'produtos:deletar_produto' produto.id %}" method="get">
                        {% csrf_token %}
                        <button type="submit" class="excluir">Excluir</button>
                    </form>
                </div>
            </div>
        {% endfor %}
        <div class="adicionar-link">
            <a href="{% url 'produtos:adicionar_produto' %}">Adicionar Novo Produto</a>
            <a href="{% url 'home' %}">Voltar para o Menu Inicial</a>
        </div>
    </div>
</body>
</html>