club_77/clientes/urls.py
from django.urls import path
from . import views

app_name = 'clientes'

urlpatterns = [
    path('', views.lista_clientes, name='lista_clientes'),
    path('adicionar/', views.adicionar_cliente, name='adicionar_cliente'),
    path('editar/<int:cliente_id>/', views.editar_cliente, name='editar_cliente'),
    path('deletar/<int:cliente_id>/', views.deletar_cliente, name='deletar_cliente'),
]

club_77/club_77/urls.py
from django.contrib import admin
from django.urls import path, include
from página_principal import views as home

urlpatterns = [
    path('', home.homepage, name='home'),
    path('admin/', admin.site.urls),
    path('produtos/', include('produtos.urls')),
    path('clientes/', include('clientes.urls')),
    path('vendas/', include('vendas.urls'))
]

club_77/produtos/urls.py
from django.urls import path
from . import views

app_name = 'produtos'

urlpatterns = [
    path('', views.lista_produtos, name='lista_produtos'),
    path('detalhes/<int:id>/', views.detalhes_produto, name='detalhes_produto'),
    path('adicionar/', views.adicionar_produto, name='adicionar_produto'),
    path('editar/<int:produto_id>/', views.editar_produto, name='editar_produto'),
    path('confirmar_exclusao/<int:produto_id>/', views.confirmar_exclusao, name='confirmar_exclusao'),
    path('deletar/<int:produto_id>/', views.deletar_produto, name='deletar_produto'),
]

club_77/página_principal/urls.py
from django.urls import path
from . import views

app_name = 'página_principal'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('produtos/', views.lista_produtos, name='lista_produtos'),
    path('clientes/', views.lista_clientes, name='lista_clientes'),
    path('vendas/', views.lista_vendas, name='lista_vendas'),
]

club_77/vendas/urls.py
from django.urls import path
from . import views

app_name = 'vendas'

urlpatterns = [
    path('', views.lista_vendas, name='lista_vendas'),
    path('adicionar/', views.adicionar_venda, name='adicionar_venda'),
    path('detalhes/<int:venda_id>/', views.detalhes_venda, name='detalhes_venda'),
    path('editar/<int:venda_id>/', views.editar_venda, name='editar_venda'),
]

club_77/página_principal/models.py
from django.db import models

# Create your models here.

club_77/página_principal/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'página_principal/pagina_principal.html')

club_77/página_principal/templates/página_principal/pagina_principal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
     <link rel="stylesheet" type="text/css" href="{% static 'página_principal/style.css' %}">
</head>
<body>
    <div class="container">
        <h1>Bem-vindo ao Sistema de Gerenciamento</h1>
        <ul class="menu">
            <li><a href="{% url 'produtos:lista_produtos' %}">Lista de Produtos</a></li>
            <li><a href="{% url 'clientes:lista_clientes' %}">Lista de Clientes</a></li>
            <li><a href="{% url 'vendas:lista_vendas' %}">Lista de Vendas</a></li>
        </ul>
    </div>
</body>
</html>