club_77/clientes/urls.py
from django.urls import path
from . import views

app_name = 'clientes'

urlpatterns = [
    path('', views.lista_clientes, name='lista_clientes'),
    path('adicionar/', views.adicionar_cliente, name='adicionar_cliente'),
    path('editar/<int:cliente_id>/', views.editar_cliente, name='editar_cliente'),
    path('deletar/<int:cliente_id>/', views.deletar_cliente, name='deletar_cliente'),
]

club_77/club_77/urls.py
from django.contrib import admin
from django.urls import path, include
from página_principal import views as home

urlpatterns = [
    path('', home.homepage, name='home'),
    path('admin/', admin.site.urls),
    path('produtos/', include('produtos.urls')),
    path('clientes/', include('clientes.urls')),
    path('vendas/', include('vendas.urls'))
]

club_77/vendas/urls.py
from django.urls import path
from . import views

app_name = 'vendas'

urlpatterns = [
    path('', views.lista_vendas, name='lista_vendas'),
    path('adicionar/', views.adicionar_venda, name='adicionar_venda'),
    path('detalhes/<int:venda_id>/', views.detalhes_venda, name='detalhes_venda'),
    path('editar/<int:venda_id>/', views.editar_venda, name='editar_venda'),
]

club_77/clientes/models.py
from django.db import models

class Cliente(models.Model):
    nome = models.CharField(max_length=100)
    telefone = models.CharField(max_length=20)
    cpf = models.CharField(max_length=14)

    def __str__(self):
        return self.nome

club_77/clientes/forms.py
from django import forms
from .models import Cliente

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nome', 'telefone', 'cpf']

club_77/clientes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Cliente
from .forms import ClienteForm

def lista_clientes(request):
    clientes = Cliente.objects.all()
    return render(request, 'clientes/lista_clientes.html', {'clientes': clientes})

def adicionar_cliente(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('clientes:lista_clientes')
    else:
        form = ClienteForm()
    return render(request, 'clientes/adicionar_cliente.html', {'form': form})

def editar_cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    if request.method == 'POST':
        form = ClienteForm(request.POST, instance=cliente)
        if form.is_valid():
            form.save()
            return redirect('clientes:lista_clientes')
    else:
        form = ClienteForm(instance=cliente)
    return render(request, 'clientes/editar_cliente.html', {'cliente': cliente, 'form': form})

def deletar_cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    if request.method == 'POST':
        cliente.delete()
        return redirect('clientes:lista_clientes')
    return redirect('clientes:lista_clientes')  # Redirecionar de volta para lista de clientes caso a solicitação não seja POST

club_77/clientes/templates/clientes/adicionar_cliente.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adicionar Cliente</title>
    <link rel="stylesheet" type="text/css" href="{% static 'clientes/styles_adicionar_cliente.css' %}">
</head>
<body>
    <div class="container">
        <h1>Adicionar Cliente</h1>
        <form method="post">
            {% csrf_token %}
            <label for="id_nome">Nome:</label>
            <input type="text" id="id_nome" name="nome" required>
            <label for="id_telefone">Telefone:</label>
            <input type="text" id="id_telefone" name="telefone" required>
            <label for="id_cpf">CPF:</label>
            <input type="text" id="id_cpf" name="cpf" required>
            <button type="submit" class="adicionar">Salvar</button>
        </form>
        <a href="{% url 'clientes:lista_clientes' %}" class="voltar">Voltar para Lista de Clientes</a>
    </div>
</body>
</html>

club_77/clientes/templates/clientes/editar_cliente.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Cliente</title>
    <link rel="stylesheet" type="text/css" href="{% static 'clientes/styles_editar_clientes.css' %}">
</head>
<body>
    <div class="container">
        <h1>Editar Cliente</h1>
        <form method="post">
            {% csrf_token %}
            <label for="id_nome">Nome:</label>
            <input type="text" id="id_nome" name="nome" value="{{ cliente.nome }}" required>
            <label for="id_telefone">Telefone:</label>
            <input type="text" id="id_telefone" name="telefone" value="{{ cliente.telefone }}" required>
            <label for="id_cpf">CPF:</label>
            <input type="text" id="id_cpf" name="cpf" value="{{ cliente.cpf }}" required>
            <button type="submit" class="salvar">Salvar Alterações</button>
            <a href="{% url 'clientes:lista_clientes' %}" class="voltar">Voltar para Lista de Clientes</a>
        </form>
    </div>
</body>
</html>

club_77/clientes/templates/clientes/lista_clientes.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Clientes</title>
    <link rel="stylesheet" type="text/css" href="{% static 'clientes/styles_lista_clientes.css' %}">
</head>
<body>
    <div class="container">
        <h1>Lista de Clientes</h1>
        {% for cliente in clientes %}
            <div class="cliente">
                <p>Nome: {{ cliente.nome }}</p>
                <p>Telefone: {{ cliente.telefone }}</p>
                <p>CPF: {{ cliente.cpf }}</p>
                <div class="botoes">
                    <a href="{% url 'clientes:editar_cliente' cliente.id %}" class="editar">Editar</a>
                    <form action="{% url 'clientes:deletar_cliente' cliente.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="excluir">Excluir</button>
                    </form>
                </div>
            </div>
        {% endfor %}
        <div class="adicionar-link">
            <a href="{% url 'clientes:adicionar_cliente' %}" class="adicionar">Adicionar Novo Cliente</a>
            <a href="{% url 'home' %}">Voltar para o Menu Inicial</a>
        </div>
    </div>
</body>
</html>